version: '3'
services:
  laravel:
    build:
      context: ./../app   # Use the current directory as context
      dockerfile: Dockerfile   # Path to the Dockerfile
    ports:
      - "8000:9000"   # Map port 8000 on host to port 9000 in the container
    volumes:
      - ./../app:/var/www   # Mount the code into the container
    networks:
      - laravel_network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: s3nh4f0rt3
      MYSQL_DATABASE: docmanager
      MYSQL_USER: docmanager
      MYSQL_PASSWORD: docmanager
    ports:
      - "3306:3306"   # Map port 3306 on host to port 3306 in the container
    networks:
      - laravel_network

networks:
  laravel_network:
