version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    working_dir: /var/www
    volumes:
      - ./../app:/var/www
      - ./fpm.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
  laravel:
    build:
      context: ./../
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ./../app:/var/www
    networks:
      - laravel-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: s3nh4f0rt3
      MYSQL_DATABASE: docmanager
      MYSQL_USER: docmanager
      MYSQL_PASSWORD: docmanager
    ports:
      - "3306:3306"   # Map port 3306 on host to port 3306 in the container
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge
