version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    working_dir: /var/www
    volumes:
      - ./../app:/var/www
      - ./fpm.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
  laravel:
    build:
      context: ./../
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ./../app:/var/www
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge
