FROM php:8.0-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./app .

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN composer install --no-scripts --no-autoloader

RUN composer dump-autoload

EXPOSE 9000
CMD ["php-fpm"]